### ISSUE TITLE
I don't understand

### ISSUE THREAD

**Issue by chili555** [roryrjb/lenovo-ideapad500s-wifi-drivers#2]
What does your script, which installs Atheros drivers and firmware, have to do with the Broadcom 14e4:43ae?

I don't understand.

**Comment by roryrjb** [comment]
@chili555 good question, and I don't really understand either. I just know that this definitely works with my Lenovo IdeaPad 500S.

**Comment by chili555** [comment]
Then I doubt you have a Broadcom.
